# Generated by Django 3.1.3 on 2020-11-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=355, null=True)),
                ('place_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Townhouse', 'Townhouse'), ('Whole bulding', 'Whole bulding'), ('Loft', 'Loft')], max_length=20)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=70, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('beds', models.IntegerField(choices=[('Studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4+')], null=True)),
                ('baths', models.IntegerField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
