# Generated by Django 3.1.3 on 2020-11-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='time',
        ),
    ]
