# Generated by Django 3.1.3 on 2020-11-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0002_remove_property_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.CharField(choices=[('Studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4+')], max_length=10, null=True),
        ),
    ]
