# Generated by Django 3.1.3 on 2020-11-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0003_auto_20201124_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
