# Generated by Django 3.1.3 on 2020-11-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0005_auto_20201126_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='beds',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4+')], max_length=10, null=True),
        ),
    ]
