# Generated by Django 3.1.3 on 2020-11-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0006_auto_20201126_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='furniture',
            field=models.CharField(choices=[('furnished', 'furnished'), ('unfurnished', 'unfurnished')], max_length=20, null=True),
        ),
    ]
