# Generated by Django 3.1.3 on 2020-11-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0007_property_furniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='baths',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4+')], max_length=10, null=True),
        ),
    ]
