# Generated by Django 3.1.3 on 2020-11-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0008_auto_20201128_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bin_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='gltf_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
