# Generated by Django 3.1.3 on 2020-11-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0010_property_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='pic2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='pic3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='pic4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='pic5',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
