# Generated by Django 3.1.3 on 2020-11-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0011_auto_20201129_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='pic4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='pic5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
