# Generated by Django 3.1.3 on 2020-11-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0012_auto_20201129_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rented',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('ending', 'ending')], max_length=10, null=True),
        ),
    ]
