# Generated by Django 3.1.3 on 2020-11-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0015_auto_20201129_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bin_file',
        ),
        migrations.RemoveField(
            model_name='property',
            name='gltf_file',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pic5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rented',
        ),
    ]
