# Generated by Django 3.1.3 on 2020-11-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerApp', '0016_auto_20201130_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bin_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='glft_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='pic4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='pic5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='renting',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('ending', 'ending')], max_length=10, null=True),
        ),
    ]
